name: Update content daily

on:
  schedule:
    - cron: '0 0 * * *' # Tous les jours à minuit UTC

jobs:
  update-content:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run update script
      run: |
        # Votre script pour récupérer et mettre à jour le contenu
        ./update_script.sh
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Update content"
        git push
